WebHostel/WebHostel/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebHostel.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "УКАЖИТЕ ЛОГИН!")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Диапазон символов : 8-20")]
        public string login { get; set; }

        [Required(ErrorMessage = "УКАЖИТЕ ПАРОЛЬ!")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Диапазон символов : 8-20")]
        public string password { get; set; }
    }
}

WebHostel/WebHostel/Models/Wirehouse_employeesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebHostel.Domain.Enum;

namespace WebHostel.Models
{
    public class Wirehouse_employeesViewModel
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string phone { get; set; }
        public WEmployeeRanks rank { get; set; }
        public string wirehouse_name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public UserStatus status { get; set; }
    }
}

WebHostel/WebHostel/Controllers/WirehouseEmployeesController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebHostel.Models;
using WebHostel.Services.Implements;

namespace WebHostel.Controllers
{
    public class Wirehouse_employeesController : Controller
    {
        private readonly WirehouseEmployeesService Service;

        public Wirehouse_employeesController(WirehouseEmployeesService _service)
        {
            Service = _service;
        }
        [HttpGet]
        public IActionResult CreateWEmployee
            ()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateWEmployee
            (Wirehouse_employeesViewModel wirehouse_Employee)
        {
            if (ModelState.IsValid)
            {
                var Response = Service.CreateWEmployee(wirehouse_Employee);
                if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                    return View();
                return RedirectToAction("Error");
            }
            return View();
        }
        [HttpGet]
        public IActionResult EditWEmployee(int id)
        {
            var Response = Service.GetWEmployees();
            if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                return View(Response.Data.FirstOrDefault(r => r.id == id));
            return RedirectToAction("Error");
        }
        [HttpPost]
        public IActionResult EditWEmployee
            (Wirehouse_employeesViewModel wirehouse_Employee)
        {
            if (ModelState.IsValid)
            {
                var Response = Service.EditWEmployee(wirehouse_Employee);
                if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    TempData["success"] = Response.Description.ToString();
                    return RedirectToAction("GetWEmployee", wirehouse_Employee);
                }
                TempData["failure"] = Response.Description.ToString();
                return View(wirehouse_Employee);
            }
            return View();
        }
        public IActionResult DeleteWEmployee(Wirehouse_employeesViewModel wirehouse_Employee)
        {
            var Response = Service.DeleteWEmployee(wirehouse_Employee);
            if (Response.StatusCode == Domain.Enum.StatusCode.OK)
            {
                TempData["success"] = Response.Description.ToString();
                return RedirectToAction("GetWEmployees");
            }
            TempData["failure"] = Response.Description.ToString();
            return RedirectToAction("GetWEmployees");
        }
        public IActionResult GetWEmployee(Wirehouse_employeesViewModel wirehouse_Employee)
        {
            var Response = Service.GetWEmployees();
            if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                return View(Response.Data.FirstOrDefault(r => r.id == wirehouse_Employee.id));
            return RedirectToAction("Error");
        }
        public IActionResult GetWEmployees()
        {
            var Response = Service.GetWEmployees();
            if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                return View(Response.Data.ToList());
            else
            {
                ModelState.AddModelError("", Response.Description);
                return View();
            }
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Log_in()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(WERegisterViewModel _employee)
        {
            if (ModelState.IsValid)
            {
                var Response = Service.Register(_employee);
                if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new System.Security.Claims.ClaimsPrincipal(Response.Data));
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", Response.Description);
            }
            return View(_employee);
        }
        [HttpPost]
        public async Task<IActionResult> Log_in(LoginViewModel _employee)
        {
            if (ModelState.IsValid)
            {
                var Response = Service.Log_in(_employee);
                if (Response.StatusCode == Domain.Enum.StatusCode.OK)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new System.Security.Claims.ClaimsPrincipal(Response.Data));
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", Response.Description);
            }
            return View();
        }

        public async Task<IActionResult> Log_out()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

WebHostel/WebHostel/Views/Wirehouse_employees/EditWEmployee.cshtml
@using WebHostel.Domain.Enum

@model WebHostel.Models.WERegisterViewModel
@{
    ViewData["Title"] = "Изменение данных";
}

<div class="nav-item">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>
<form asp-controller="Wirehouse_employees" asp-action="EditWEmployee">
    <div class="card col-md-8">
        <div class="card-header text-center">
        <label>Изменение данных работника склада</label>
    </div>
        <div class="card-body">
            <div class="card-columns">
                <label>ФИО: </label>
                <input asp-for="fullname" name="fullname" placeholder="ФИО: " value="@Model.fullname"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Номер телефона: </label>
                <input asp-for="phone" name="phone" placeholder="Номер телефона: " value="@Model.phone"/>
            </div>
            <br />
            <div class="card-columns">
                 Должность:
                <select asp-for="rank" name="rank" asp-items="@Html.GetEnumSelectList<WEmployeeRanks>()">
                    <option value="@Model.rank">Выбрать</option>
                </select>
            </div>
            <br />
            <div class="card-columns">
                Статус:
                <select asp-for="status" name="status" asp-items="@Html.GetEnumSelectList<UserStatus>()">
                    <option value="@Model.status">Выбрать</option>
                </select>
            </div>
            <br />
            <div class="card-columns">
                <label>Склад: </label>
                <input asp-for="wirehouse_name" name="wirehouse_name" placeholder="Кафе: " value="@Model.wirehouse_name"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Логин: </label>
                <input asp-for="login" name="login" placeholder="Логин: " value="@Model.login"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Пароль: </label>
                <input asp-for="password" name="password" placeholder="Пароль: " value="@Model.password"/>
            </div>
            <br />
            <div class="card-columns">
                <button type="submit">Изменить данные</button>
            </div>
            <br />
            <div class="card-footer text-center"><label>Обязательно проверьте введённые данные!</label></div>
        </div>
        </div>
</form>

WebHostel/WebHostel/Views/Wirehouse_employees/GetWEmployee.cshtml
@using WebHostel.Domain.Enum
@using WebHostel.Domain.Functions
@model WebHostel.Models.Wirehouse_employeesViewModel    
<div class="card">
        <div class="card-header">
           <label>@Model.fullname</label>
        </div>
        <div class="card-body">
            <div class="card-columns">
                <label>Номер телефона: @Model.phone</label>
            </div>
            <div class="card-columns">
                <label>Должность: @EnumExtension.GetDisplayName(Model.rank)</label>
            </div>
            <div class="card-columns">
                <label>Ваш склад: <a asp-controller="Wirehouse" asp-action="GetWirehouse" asp-route-title="@Model.wirehouse_name">
                @Model.wirehouse_name</a></label>
            </div>
            <div class="card-columns">
                <label>Логин: @Model.login</label>
            </div>
        </div>
        <div class="card-footer">
                @if (User.IsInRole("employee") || User.IsInRole("admin")) 
                {
                    <a class="btn btn-warning" asp-controller="Wirehouse_employees" asp-action="EditWEmployee" asp-route-id="@Model.id" >Редактировать</a>
                }
        </div>
    </div>
<br />

WebHostel/WebHostel/Views/Wirehouse_employees/GetWEmployees.cshtml
@model List<WebHostel.Models.Wirehouse_employeesViewModel>
<div class="text-right">
<a class="btn btn-warning" asp-controller="Wirehouse_employees" asp-action="Register">Добавить работника склада</a>
</div>
@if (Model == null)
{
    <div asp-validation-summary="All" class="text-warning"></div>
}
@if(Model != null)
@foreach (var e in Model)
{
    <div class="card">
        <div class="card-header">
           <label> @e.fullname</label>
        </div>
        <div class="card-body">
            <div class="card-columns">
                <label>Номер телефона: @e.phone</label>
            </div>
        </div>
        <div class="card-footer">
                <a class="btn btn-danger" asp-action="DeleteWEmployee" asp-route-id="@e.id">Удалить</a>
                <label> || </label>
                <a class="btn btn-warning" asp-action="EditWEmployee" asp-route-id="@e.id">Редактировать</a>
                <label> || </label>
                <a class="btn btn-info" asp-action="GetWEmployee" asp-route-id="@e.id">Информация</a>
        </div>
    </div>
<br />
}

WebHostel/WebHostel/Views/Wirehouse_employees/Log_in.cshtml
@model WebHostel.Models.LoginViewModel
@{
    ViewData["Title"] = "Вход";
}

<div class="nav-item">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>
<form asp-controller="Wirehouse_employees" asp-action="Log_in">
    <div class="card col-md-12 text-center">
        <div class="card-header text-center"><label>Вход в кабинет (работник-склад)</label></div>
        <div class="card-body">
            <div class="card-columns">
                <label>Логин: </label>
                 <input asp-for="login" name="login" placeholder="Логин "/>
            </div>
            <br />
            <div class="card-columns">
                <label>Пароль: </label>
                 <input asp-for="password" name="password" placeholder="Пароль "/>
            </div>
            <br />
            <div class="card-columns">
                <button class="btn btn-warning" type="submit">Войти в кабинет</button>
            </div>
        </div>
        </div>
</form>

WebHostel/WebHostel/Views/Wirehouse_employees/Register.cshtml
@using WebHostel.Domain.Enum

@model WebHostel.Models.WERegisterViewModel
@{
    ViewData["Title"] = "Регистраиця";
}

<div class="nav-item">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>
<form asp-controller="Wirehouse_employees" asp-action="Register">
    <div class="card col-md-8">
        <div class="card-header text-center">Регистрация работника отеля</div>
        <div class="card-body">
            <div class="card-columns">
                <label>ФИО: </label>
                <input asp-for="fullname" name="fullname" placeholder="ФИО"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Номер телефона: </label>
                <input asp-for="phone" name="phone" placeholder="Номер телефона:"/>
            </div>
            <br />
            <div class="card-columns">
                Должность:
                <select asp-for="rank" name="rank" asp-items="@Html.GetEnumSelectList<WEmployeeRanks>()">
                    <option value="">Выбрать</option>
                </select>
            </div>

            <br />
            <div class="card-columns">
                Статус:
                <select asp-for="status" name="status" asp-items="@Html.GetEnumSelectList<UserStatus>()">
                    <option value="">Выбрать</option>
                </select>
            </div>
            <br />
            <div class="card-columns">
                <label>Склад: </label>
                 <input asp-for="wirehouse_name" name="wirehouse_name" placeholder="Склад:"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Логин: </label>
                 <input asp-for="login" name="login" placeholder="Логин:"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Пароль: </label>
                <input asp-for="password" name="password" placeholder="Пароль:"/>
            </div>
            <br />
            <div class="card-columns">
                <label>Повторите пароль: </label>
                <input asp-for="Confirm_password" name="Confirm_password" placeholder="Повторите пароль "/>
            </div>
            <br />
            <div class="card-columns">
                <button class="btn btn-primary" type="submit">Регистраиця</button>
            </div>
            <br />
            <div class="card-footer text-center">Обязательно проверьте введённые данные!</div>
        </div>
        </div>
</form>