WebSchoolMVC/WebSchoolMVC/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class AdminsController : Controller
    {
        private readonly IAdminsInterface _repo;

        public AdminsController(IAdminsInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<ActionResult> GetById(int Id)
        {

            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();

        }

        [HttpGet]
        public IActionResult AdminLogIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdminLogIn(LogInViewModel userdata)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.FindAndAuthenticate(userdata.Login, userdata.Password);
                if (OperationResult.IsSuccessful)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new System.Security.Claims.ClaimsPrincipal(OperationResult.Data));
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", OperationResult.Description);
                return View(userdata);
            }
            return View(userdata);
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Controllers/GroupController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Domain.Entity;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupInterface _repo;

        public GroupController(IGroupInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var OperationResult = await _repo.GetAll();

            if (OperationResult.IsSuccessful)
                return (OperationResult.Data is not null) ? View(OperationResult.Data) : RedirectToAction("GetAll");


            return BadRequest();
        }

        // GET: HomeController1/Details/5
        [HttpGet]
        public async Task<ActionResult> GetById(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();

        }

        // GET: HomeController1/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var OperationResult = await Task.FromResult(PartialView("Create"));
            return OperationResult;
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(GroupViewModel group)
        {

            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Create(new Group
                {
                    Title = group.Title
                });

                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }

            return PartialView("Create", group);
        }

        // GET: HomeController1/Edit/5
        [HttpGet]
        public async Task<ActionResult> Update(int Id)
        {
            var OperationResult = await _repo.GetById(Id);
            var group = new GroupViewModel
            {
                Id = OperationResult.Data.Id,
                Title = OperationResult.Data.Title,
                Teacher_Id = OperationResult.Data.Teacher_Id.HasValue ? OperationResult.Data.Teacher_Id : null
            };
            return PartialView("Update", group);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(GroupViewModel group)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Edit(new Group
                {
                    Id = group.Id,
                    Title = group.Title,
                    Teacher_Id = group.Teacher_Id.HasValue ? group.Teacher_Id : null
                });

                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }

            return PartialView("Update", group);
        }

        // GET: HomeController1/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Delete", OperationResult.Data);

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        // POST: HomeController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Group group)
        {
            var OperationResult = await _repo.Delete(group);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Controllers/JournalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Domain.Entity;
using WebSchoolMVC.Domain.Response;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class JournalController : Controller
    {
        private readonly IJournalInterface _repo;

        public JournalController(IJournalInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<ActionResult> Create(int Student_Id)
        {
            var OperationResult = await _repo.GetSubjectsByTeacherId(int.Parse(User.FindFirst(ClaimTypes.Sid).Value));
            return PartialView("Create", new JournalViewModel
            {
                Student_Id = Student_Id,
                Subjects = new SelectList(OperationResult.Data, "Id", "Title")
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(JournalViewModel newNote)
        {
            if (!ModelState.IsValid)
                return PartialView("Create", newNote);

            var OperationResult = await _repo.Create(new Journal 
            { 
                Student_Id = newNote.Student_Id, 
                Subject_Id = newNote.Subject_Id,
                Mark = newNote.Mark,
                MarkingDate = DateTime.Today
            });
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(int Student_Id)
        {
            IBaseResponse<IEnumerable<Journal>> OperationResult;

            if (Student_Id != 0)
                OperationResult = await _repo.GetAllByStudentId(Student_Id);
            else
                OperationResult = await _repo.GetAll();

            if (OperationResult.IsSuccessful)
                return (OperationResult.Data is not null) ? View(OperationResult.Data) : RedirectToAction("GetAll");

            return BadRequest();
        }
        [HttpGet]
        public async Task<IActionResult> GetById(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var OperationResult = await _repo.GetById(Id);
            if (OperationResult.IsSuccessful)
                return PartialView("Delete", OperationResult.Data);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Journal note)
        {
            var OperationResult = await _repo.Delete(note);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Domain.Entity;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomInterface _repo;

        public RoomController(IRoomInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var OperationResult = await _repo.GetAll();

            if (OperationResult.IsSuccessful)
                return (OperationResult.Data is not null) ? View(OperationResult.Data) : RedirectToAction("GetAll");

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();

        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var OperationResult = await Task.FromResult(PartialView("Create"));
            return OperationResult;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomViewModel room)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Create(new Room
                {
                    Number = room.Number,
                    Floor = (int)room.Floor
                });
                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }
            return PartialView("Create", room);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Update", new RoomViewModel
                {
                    Id = OperationResult.Data.Id,
                    Number = OperationResult.Data.Number,
                    Floor = OperationResult.Data.Floor,
                    Teacher_Id = OperationResult.Data.Teacher_Id
                });

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(RoomViewModel room)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Edit(new Room
                {
                    Id = room.Id,
                    Number = room.Number,
                    Floor = (int)room.Floor,
                    Teacher_Id = room.Teacher_Id
                });
                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }
            return PartialView("Update", room);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Delete", OperationResult.Data);

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Room room)
        {
            var OperationResult = await _repo.Delete(room);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public IActionResult AddCaretaker(int Id, int Teacher_Id)
        {
            var OperationResult = _repo.AddCaretaker(Id, Teacher_Id);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public IActionResult RemoveCaretaker(int Id)
        {
            var OperationResult = _repo.RemoveCaretaker(Id);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Views/Shared/_ErrorPartial.cshtml
<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Info</h5>
                <button type="button" class="btn-close" onclick="closePartialClick(this)" aria-label="Close">
                    <span area-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <i class="bi bi-exclamation-triangle" style="font-size:200px; margin-bottom:30px"></i>
                    <p class="text-center">UNEXPECTED ERROR</p>
                </div>
            </div>
            <div class="modal-footer" style="justify-content:center">
                <button onclick="closeAfterOperationPartialClick(this)" type="button" class="btn btn-primary"><i class="bi bi-x-circle"></i> OK</button>
            </div>
        </div>
    </div>
</div>

WebSchoolMVC/WebSchoolMVC/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSchoolMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Lumen.css" />
    <link rel="stylesheet" href="~/css/CustomCSS.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">WebSchoolMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Student" asp-action="GetAll">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Teacher" asp-action="GetAll">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Group" asp-action="GetAll">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Room" asp-action="GetAll">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Journal" asp-action="GetAll">Marks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Subject" asp-action="GetAll">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-light" asp-area="" asp-controller="Timetable" asp-action="GetAll">Timetables</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" style="color:white">Account</a>
                            <div class="dropdown-menu">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <a class="dropdown-item" asp-controller="Student" asp-action="StudentLogIn">Log in as student</a>
                                    <a class="dropdown-item" asp-controller="Teacher" asp-action="TeacherLogIn">Log in as teacher</a>
                                    <a class="dropdown-item" asp-controller="Admins" asp-action="AdminLogIn">Log in as admin</a>
                                }
                                else
                                {
                                    if (User.IsInRole(UserStatus.Student.ToString()))
                                    {
                                        <a class="dropdown-item" asp-controller="Student" asp-action="GetById" asp-route-Id="@int.Parse(User.FindFirst(ClaimTypes.Sid).Value)">My profile</a>

                                    }
                                    else if (User.IsInRole(UserStatus.Teacher.ToString()))
                                    {
                                        <a class="dropdown-item" asp-controller="Teacher" asp-action="GetById" asp-route-Id="@int.Parse(User.FindFirst(ClaimTypes.Sid).Value)">My profile</a>
                                    }
                                    else if (User.IsInRole(UserStatus.Admin.ToString()))
                                    {
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="GetById" asp-route-Id="@int.Parse(User.FindFirst(ClaimTypes.Sid).Value)">My profile</a>
                                    }
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Home" asp-action="LogOut">Log out</a>
                                }
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebSchoolMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebSchoolMVC/WebSchoolMVC/Views/Shared/_OperationDetailsPartial.cshtml
@model WebSchoolMVC.Models.OperationViewModel

<div class="modal fade" id="operationDetails" style="position:center">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Info</h5>
                <button type="button" class="btn-close" onclick="closePartialClick(this)" aria-label="Close">
                    <span area-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                @if (Model.Status == OperationStatus.Succeeded)
                {
                    <div class="row">
                        <div class="col text-center">
                            <i class="bi bi-bookmark-check link-success" style="font-size:200px"></i>
                        </div>
                    </div>
                    <div class="row" style="justify-content:center">
                        <div class="col text-center">
                            OPERATION SUCCEEDED!
                        </div>
                    </div>
                }
                else if (Model.Status == OperationStatus.Failed)
                {
                    <div class="row" style="justify-content:center">
                        <div class="col">
                            <i class="bi bi-bookmark-dash link-danger" style="height:32px; width:32px"></i>
                        </div>
                    </div>
                    <div class="row" style="justify-content:center">
                        <div class="col">
                            OPERATION FAILED!
                        </div>
                    </div>
                    <div class="row" style="justify-content:center">
                        <div class="col">
                            Details: @Model.Message
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer" style="display:flex; justify-content:center">
                <button onclick="closeAfterOperationPartialClick(this)" type="button" class="btn btn-primary"><i class="bi bi-journal-check"></i> OK</button>
            </div>
        </div>
    </div>
</div>