WebSchoolMVC/WebSchoolMVC/Models/SubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebSchoolMVC.Models
{
    public class SubjectViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is empty")]
        [MinLength(1, ErrorMessage = "Title must be at least 1 charater")]
        [MaxLength(45, ErrorMessage = "Title must not be longer than 45 characters")]
        public string Title { get; set; }
    }
}

WebSchoolMVC/WebSchoolMVC/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Domain.Entity;
using WebSchoolMVC.Domain.Response;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubjectInterface _repo;

        public SubjectController(ISubjectInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll(int Teacher_Id)
        {
            IBaseResponse<IEnumerable<Subject>> OperationResult;

            if (Teacher_Id != 0)
                OperationResult = await _repo.GetAllByTeacherId(Teacher_Id);
            else
                OperationResult = await _repo.GetAll();

                return OperationResult.IsSuccessful && (OperationResult.Data is not null) ? View(OperationResult.Data) : BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();

        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var OperationResult = await Task.FromResult(PartialView("Create"));
            return OperationResult;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubjectViewModel subject)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Create(new Subject
                {
                    Title = subject.Title
                });
                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }
            return PartialView("Create", subject);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Delete", OperationResult.Data);

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Subject subject)
        {
            var OperationResult = await _repo.Delete(subject);

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public async Task<IActionResult> AddTeacher(int Subject_Id, int Teacher_Id)
        {
            var OperationResult = await _repo.AddTeacher(Subject_Id, Teacher_Id);
            var GetSubjectResult = await _repo.GetById(Subject_Id);
            return OperationResult.IsSuccessful && GetSubjectResult.IsSuccessful ? RedirectToAction("GetById", "Subject", GetSubjectResult.Data) : BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> RemoveTeacher(int Subject_Id, int Teacher_Id)
        {
            var OperationResult = await _repo.RemoveTeacher(Subject_Id, Teacher_Id);
            var GetSubjectResult = await _repo.GetById(Subject_Id);
            return OperationResult.IsSuccessful && GetSubjectResult.IsSuccessful ? RedirectToAction("GetById", "Subject", GetSubjectResult.Data) : BadRequest();
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSchoolMVC.DataAccess.Interfaces;
using WebSchoolMVC.Domain.Entity;
using WebSchoolMVC.Domain.Enum;
using WebSchoolMVC.Models;

namespace WebSchoolMVC.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherInterface _repo;

        public TeacherController(ITeacherInterface repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public async Task<ActionResult> GetAll(TeacherOrderBy teacherOrderByCondition)
        {
            var OperationResult = await _repo.GetAll();
            if (OperationResult.IsSuccessful)
            {
                var ResultList = OperationResult.Data.ToList();
                switch (teacherOrderByCondition)
                {
                    case TeacherOrderBy.FullnameAsc:
                        {
                            return View(ResultList.OrderBy(x => x.Fullname).ToList());
                        }
                    case TeacherOrderBy.FullnameDesc:
                        {
                            return View(ResultList.OrderByDescending(x => x.Fullname).ToList());
                        }
                    default:
                        {
                            return View(ResultList.ToList());
                        }
                }
            }
            return BadRequest();

        }

        [HttpGet]
        public async Task<ActionResult> GetById(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            return OperationResult.IsSuccessful ? OperationResult.Data is not null ? View(OperationResult.Data) : RedirectToAction("GetAll") : BadRequest();
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var OperationResult = await Task.FromResult(PartialView("Create"));
            return OperationResult;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TeacherViewModel teacher)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Create(new Teacher
                {
                    Fullname = teacher.Fullname,
                    Address = teacher.Address,
                    MobileNumber = teacher.MobileNumber,
                    Login = teacher.Login,
                    Password = teacher.Password,
                    Status = (int)UserStatus.Teacher

                });
                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }
            return PartialView("Create", teacher);
        }

        [HttpGet]
        public async Task<ActionResult> Update(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Update", new TeacherViewModel 
                {
                    Id = OperationResult.Data.Id,
                    Fullname = OperationResult.Data.Fullname,
                    Address = OperationResult.Data.Address,
                    MobileNumber = OperationResult.Data.MobileNumber,
                    Login = OperationResult.Data.Login,
                    Password = OperationResult.Data.Password
                });

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(TeacherViewModel teacher)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.Edit(new Teacher
                {
                    Id = teacher.Id,
                    Fullname = teacher.Fullname,
                    Address = teacher.Address,
                    MobileNumber = teacher.MobileNumber,
                    Login = teacher.Login,
                    Password = teacher.Password,
                    Status = (int)UserStatus.Teacher

                });
                return PartialView("_OperationDetailsPartial", new OperationViewModel
                {
                    Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                    Message = OperationResult.Description
                });
            }
            return PartialView("Update", teacher);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int Id)
        {
            var OperationResult = await _repo.GetById(Id);

            if (OperationResult.IsSuccessful)
                return PartialView("Delete", OperationResult.Data);

            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Teacher teacher)
        {
            var OperationResult = await _repo.Delete(teacher);
            return PartialView("_OperationDetailsPartial", new OperationViewModel
            {
                Status = OperationResult.IsSuccessful ? OperationStatus.Succeeded : OperationStatus.Failed,
                Message = OperationResult.Description
            });
        }

        [HttpGet]
        public IActionResult TeacherLogIn()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> TeacherLogIn(LogInViewModel userdata)
        {
            if (ModelState.IsValid)
            {
                var OperationResult = await _repo.FindAndAuthenticate(userdata.Login, userdata.Password);
                if (OperationResult.IsSuccessful)
                {
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new System.Security.Claims.ClaimsPrincipal(OperationResult.Data));
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", OperationResult.Description);
                return View(userdata);
            }
            return View(userdata);
        }
    }
}

WebSchoolMVC/WebSchoolMVC/Views/Subject/Create.cshtml
@model WebSchoolMVC.Models.SubjectViewModel

<div class="modal fade" id="CreateSubject" style="position:center">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">New subject</h5>
                <button type="button" class="btn-close" onclick="closePartialClick(this)" aria-label="Close">
                    <span area-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <form id="SubjectData" asp-controller="Subject" asp-action="Create" method="post">
                    <div class="form-group">
                        <label for="sTitle" class="form-label">Title</label>
                        <input asp-for="Title" class="form-control" id="sTitle" placeholder="Enter title">
                        <span class="form-text text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <div asp-validation-summary="ModelOnly" class="form-text text-danger text-center fs-5"></div>
                    </div>
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                </form>
            </div>
            <div class="modal-footer" style="justify-content:center">
                <button onclick="saveClick(this)" type="button" class="btn btn-success"><i class="bi bi-cassette"></i> Add</button>
                <button onclick="closePartialClick(this)" type="button" class="btn btn-danger"><i class="bi bi-x-circle"></i> Cancel</button>
            </div>
        </div>
    </div>
</div>

WebSchoolMVC/WebSchoolMVC/Views/Subject/Delete.cshtml
@model WebSchoolMVC.Domain.Entity.Subject

<div class="modal fade" id="CreateSubject" style="position:center">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete subject (SID: @Model.Id)</h5>
                <button type="button" class="btn-close" onclick="closePartialClick(this)" aria-label="Close">
                    <span area-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <form id="SubjectData" asp-controller="Subject" asp-action="Create" method="post">
                    <input asp-for="Id" type="hidden" value="@Model.Id" />
                    <div class="form-group">
                        <label for="sTitle" class="form-label">Title: @Model.Title</label>
                    </div>
                </form>
            </div>
            <div class="modal-footer" style="justify-content:center">
                <button onclick="saveClick(this)" type="button" class="btn btn-danger"><i class="bi bi-cassette"></i> Proceed</button>
                <button onclick="closePartialClick(this)" type="button" class="btn btn-success"><i class="bi bi-x-circle"></i> Cancel</button>
            </div>
        </div>
    </div>
</div>

WebSchoolMVC/WebSchoolMVC/Views/Subject/GetAll.cshtml
@model List<WebSchoolMVC.Domain.Entity.Subject>

<div id="mainDiv">
    <div class="text-lg-center fs-1" style="margin-bottom:60px">
        Subjects <i id="stCreate" class="bi bi-plus-circle link-success" data-url="@Url.Action("Create","Subject")" onclick="openPartialClick(this)" style="cursor:pointer"></i>
    </div>
    <div id="subjectList" style="display:grid; grid-template-columns: 1fr 1fr 1fr; column-gap:10px; row-gap:25px; max-height:500px; overflow-y: scroll; background-color: rgb(230, 230, 230)">
        @foreach (var x in Model)
        {
            <div class="card">
                <div class="card-header">
                        <label class="card-title fs-3">
                            @x.Title
                        </label>
                        <br />
                        <label class="card-subtitle">
                            SUBJECT ID: @x.Id
                        </label>
                    </div>
                <div class="card-footer" style="display:flex; justify-content: center">
                    <a class="btn btn-primary" asp-action="GetById" asp-route-Id="@x.Id">Details</a>
                </div>
            </div>
        }
    </div>
</div>

WebSchoolMVC/WebSchoolMVC/Views/Subject/GetById.cshtml
@using System.Security.Claims
@model WebSchoolMVC.Domain.Entity.Subject

<div id="mainDiv">
    <div class="text-lg-center fs-1" style="margin-bottom:60px">
        Subjects <i id="stCreate" class="bi bi-plus-circle link-success" data-url="@Url.Action("Create","Subject")" onclick="openPartialClick(this)" style="cursor:pointer"></i>
    </div>
    <div id="subjectList" class="row" style="justify-content:center">
        <div class="col-lg-7">
            <div class="card">
                <div class="card-header" position="relative">
                    <div class="dropdown" style="position:absolute; top:20px; right:20px; ">
                        <a class="btn btn-outline-primary" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="bi bi-list-ul" style="font-size:24px"></i></a>
                        <div class="dropdown-menu">
                            @if (User.IsInRole(UserStatus.Teacher.ToString()) && !Model.Teachers.Any(x => x.Id == int.Parse(User.FindFirst(ClaimTypes.Sid).Value)))
                            {
                                <a class="dropdown-item" asp-action="AddTeacher" asp-route-Subject_Id="@Model.Id" asp-route-Teacher_Id="@int.Parse(User.FindFirst(ClaimTypes.Sid).Value)"><i class="bi bi-person-plus"></i> Begin teaching</a>
                                <div class="dropdown-divider"></div>
                            }
                            else if (User.IsInRole(UserStatus.Teacher.ToString()) && Model.Teachers.Any(x => x.Id == int.Parse(User.FindFirst(ClaimTypes.Sid).Value)))
                            {
                                <a class="dropdown-item" asp-action="RemoveTeacher" asp-route-Subject_Id="@Model.Id" asp-route-Teacher_Id="@int.Parse(User.FindFirst(ClaimTypes.Sid).Value)"><i class="bi bi-person-dash"></i> End teaching</a>
                                <div class="dropdown-divider"></div>
                            }
                            <button class="dropdown-item" onclick="openPartialClick(this)" asp-action="Update" asp-route-Id="@Model.Id"><i class="bi bi-pencil-square"></i> Edit</button>
                            <button class="dropdown-item" onclick="openPartialClick(this)" asp-action="Delete" asp-route-Id="@Model.Id"><i class="bi bi-trash3-fill"></i> Delete</button>
                        </div>
                    </div>
                    <label class="card-title fs-3">
                        @Model.Title
                    </label>
                    <br />
                    <label class="card-subtitle">
                        SUBJECT ID: @Model.Id
                    </label>
                </div>
                <div class="card-body">
                    <p class="card-title fs-4">Teachers</p>
                    <div class="row" style="justify-content:center; overflow-y:scroll; max-height:300px">
                        @foreach (var x in Model.Teachers)
                        {
                            <div class="col-lg-6" style="margin-bottom:25px">
                                <div class="card">
                                    <div class="card-header">
                                        <label class="card-title fs-3" style="margin-bottom:6px">
                                            @x.Fullname
                                        </label>
                                        <label class="card-subtitle">
                                            TEACHER ID: @x.Id
                                        </label>
                                    </div>
                                    <div class="card-body">
                                        <div class="card-group">
                                            <label class="card-text">Phone: @x.MobileNumber</label>
                                        </div>
                                        <div class="card-group">
                                            <a class="link-primary" asp-controller="Teacher" asp-action="GetById" asp-route-Id="@x.Id">Details</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        }
                    </div>

                </div>
                <div class="card-footer" style="display:flex; justify-content: center">
                </div>
            </div>
        </div>
    </div>
</div>